
# This file is automatically generated, you probably don't want to edit this

jammGLMOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jammGLMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            mediators = NULL,
            factors = NULL,
            covs = NULL,
            modelTerms = NULL,
            ciType = "standard",
            ciWidth = 95,
            bootN = 1000,
            contrasts = NULL,
            showRealNames = TRUE,
            showContrastCode = FALSE,
            bogus = FALSE,
            simpleScale = "mean_sd",
            cvalue = 1,
            percvalue = 25,
            simpleScaleLabels = "labels",
            scaling = NULL,
            tableOptions = list(
                "beta"),
            mediatorsTerms = list(
                list()),
            moderatorsTerms = list(
                list()), ...) {

            super$initialize(
                package='jamm',
                name='jammGLM',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                permitted=list(
                    "numeric"))
            private$..mediators <- jmvcore::OptionVariables$new(
                "mediators",
                mediators,
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "standard",
                    "bca.simple",
                    "perc",
                    "norm",
                    "none"),
                default="standard")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "deviation",
                                "simple",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="deviation"))))
            private$..showRealNames <- jmvcore::OptionBool$new(
                "showRealNames",
                showRealNames,
                default=TRUE)
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..bogus <- jmvcore::OptionBool$new(
                "bogus",
                bogus,
                default=FALSE)
            private$..simpleScale <- jmvcore::OptionList$new(
                "simpleScale",
                simpleScale,
                options=list(
                    "mean_sd",
                    "percent"),
                default="mean_sd")
            private$..cvalue <- jmvcore::OptionNumber$new(
                "cvalue",
                cvalue,
                default=1)
            private$..percvalue <- jmvcore::OptionNumber$new(
                "percvalue",
                percvalue,
                default=25,
                min=5,
                max=50)
            private$..simpleScaleLabels <- jmvcore::OptionList$new(
                "simpleScaleLabels",
                simpleScaleLabels,
                options=list(
                    "labels",
                    "values",
                    "values_labels"),
                default="labels")
            private$..scaling <- jmvcore::OptionArray$new(
                "scaling",
                scaling,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "scaling",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "centered",
                                "standardized",
                                "none"),
                            default="centered"))))
            private$..tableOptions <- jmvcore::OptionNMXList$new(
                "tableOptions",
                tableOptions,
                options=list(
                    "component",
                    "beta"),
                default=list(
                    "beta"))
            private$..mediatorsTerms <- jmvcore::OptionArray$new(
                "mediatorsTerms",
                mediatorsTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "mediatorsTerms",
                    NULL))
            private$..moderatorsTerms <- jmvcore::OptionArray$new(
                "moderatorsTerms",
                moderatorsTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "moderatorsTerms",
                    NULL))

            self$.addOption(private$..dep)
            self$.addOption(private$..mediators)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..ciType)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showRealNames)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..bogus)
            self$.addOption(private$..simpleScale)
            self$.addOption(private$..cvalue)
            self$.addOption(private$..percvalue)
            self$.addOption(private$..simpleScaleLabels)
            self$.addOption(private$..scaling)
            self$.addOption(private$..tableOptions)
            self$.addOption(private$..mediatorsTerms)
            self$.addOption(private$..moderatorsTerms)
        }),
    active = list(
        dep = function() private$..dep$value,
        mediators = function() private$..mediators$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        modelTerms = function() private$..modelTerms$value,
        ciType = function() private$..ciType$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        contrasts = function() private$..contrasts$value,
        showRealNames = function() private$..showRealNames$value,
        showContrastCode = function() private$..showContrastCode$value,
        bogus = function() private$..bogus$value,
        simpleScale = function() private$..simpleScale$value,
        cvalue = function() private$..cvalue$value,
        percvalue = function() private$..percvalue$value,
        simpleScaleLabels = function() private$..simpleScaleLabels$value,
        scaling = function() private$..scaling$value,
        tableOptions = function() private$..tableOptions$value,
        mediatorsTerms = function() private$..mediatorsTerms$value,
        moderatorsTerms = function() private$..moderatorsTerms$value),
    private = list(
        ..dep = NA,
        ..mediators = NA,
        ..factors = NA,
        ..covs = NA,
        ..modelTerms = NA,
        ..ciType = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..contrasts = NA,
        ..showRealNames = NA,
        ..showContrastCode = NA,
        ..bogus = NA,
        ..simpleScale = NA,
        ..cvalue = NA,
        ..percvalue = NA,
        ..simpleScaleLabels = NA,
        ..scaling = NA,
        ..tableOptions = NA,
        ..mediatorsTerms = NA,
        ..moderatorsTerms = NA)
)

jammGLMResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        pathmodelgroup = function() private$.items[["pathmodelgroup"]],
        models = function() private$.items[["models"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM Mediation Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`="")),
                clearWith=list(
                    "dep",
                    "mediators",
                    "factors",
                    "covs",
                    "modelTerms",
                    "fixedIntercept",
                    "moderatorsTerms")))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    pathmodel = function() private$.items[["pathmodel"]],
                    pathnotes = function() private$.items[["pathnotes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathmodelgroup",
                            title="Path Model")
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="pathmodel",
                            title="Model Diagram",
                            width=600,
                            height=500,
                            renderFun=".showDiagram",
                            clearWith=list(
                                "dep",
                                "mediatorsTerms",
                                "modelTerms",
                                "moderatorsTerms")))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pathnotes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="info", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    moderationEffects = function() private$.items[["moderationEffects"]],
                    main = function() private$.items[["main"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Mediation")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="moderationEffects",
                            title="Moderation effects (interations)",
                            visible=FALSE,
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "fixedIntercept",
                                "simpleScale"),
                            columns=list(
                                list(
                                    `name`="mod", 
                                    `title`="Moderator", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="target", 
                                    `title`="Interaction", 
                                    `type`="text"),
                                list(
                                    `name`="label", 
                                    `title`="Contrasts", 
                                    `visible`=FALSE, 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `visible`="(tableOptions:beta)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Indirect and Total Effects",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "fixedIntercept",
                                "simpleScale"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="source", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="label", 
                                    `title`="Contrasts", 
                                    `visible`=FALSE, 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `visible`="(tableOptions:beta)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible=FALSE,
                            clearWith=list(
                                "contrasts"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="$key",
                                columns=list(
                                    list(
                                        `name`="rnames", 
                                        `title`="Name", 
                                        `type`="text"),
                                    list(
                                        `name`="clabs", 
                                        `title`="Contrast", 
                                        `type`="text")))))}))$new(options=options))}))

jammGLMBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jammGLMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'jamm',
                name = 'jammGLM',
                version = c(0,0,2),
                options = options,
                results = jammGLMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' GLM Mediation Model
#'
#' GLM mediation model
#'
#' @examples
#' data('ToothGrowth')
#'
#' mixed(ToothGrowth, dep = 'len', factors = 'supp', covs = 'dose')
#'
#' @param data the data as a data frame
#' @param dep a string naming the dependent variable from \code{data},
#'   variable must be numeric
#' @param mediators a vector of strings naming the mediators from \code{data}
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}
#' @param covs a vector of strings naming the covariates from \code{data}
#' @param modelTerms a list of character vectors describing fixed effects
#'   terms
#' @param ciType Choose the confidence interval type
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param contrasts a list of lists specifying the factor and type of contrast
#'   to use, one of \code{'deviation'}, \code{'simple'}, \code{'difference'},
#'   \code{'helmert'}, \code{'repeated'} or \code{'polynomial'}
#' @param showRealNames \code{TRUE} or \code{FALSE} (default), provide raw
#'   names of the contrasts variables
#' @param showContrastCode \code{TRUE} or \code{FALSE} (default), provide
#'   contrast coefficients tables
#' @param bogus \code{a bogus option to define a label without visible
#'   children}
#' @param simpleScale \code{'mean_sd'} (default), \code{'custom'} , or
#'   \code{'custom_percent'}. Use to condition the covariates (if any)
#' @param cvalue offset value for conditioning
#' @param percvalue offset value for conditioning
#' @param simpleScaleLabels .
#' @param scaling a list of lists specifying the covariates scaling, one of
#'   \code{'centered to the mean'}, \code{'standardized'}, or \code{'none'}.
#'   \code{'none'} leaves the variable as it is
#' @param tableOptions .
#' @param mediatorsTerms a list of lists specifying the models for with the
#'   mediators as dependent variables.
#' @param moderatorsTerms a list of lists specifying the the IV which
#'   moderatorate each mediated effect.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathmodelgroup$pathmodel} \tab \tab \tab \tab \tab a path model \cr
#'   \code{results$pathmodelgroup$pathnotes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$moderationEffects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$contrastCodeTables} \tab \tab \tab \tab \tab an array of contrast coefficients tables \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
jammGLM <- function(
    data,
    dep = NULL,
    mediators = NULL,
    factors = NULL,
    covs = NULL,
    modelTerms = NULL,
    ciType = "standard",
    ciWidth = 95,
    bootN = 1000,
    contrasts = NULL,
    showRealNames = TRUE,
    showContrastCode = FALSE,
    bogus = FALSE,
    simpleScale = "mean_sd",
    cvalue = 1,
    percvalue = 25,
    simpleScaleLabels = "labels",
    scaling = NULL,
    tableOptions = list(
                "beta"),
    mediatorsTerms = list(
                list()),
    moderatorsTerms = list(
                list())) {

    if ( ! requireNamespace('jmvcore'))
        stop('jammGLM requires jmvcore to be installed (restart may be required)')

    if (missing(data))
        data <- jmvcore:::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(mediators), mediators, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL))

    options <- jammGLMOptions$new(
        dep = dep,
        mediators = mediators,
        factors = factors,
        covs = covs,
        modelTerms = modelTerms,
        ciType = ciType,
        ciWidth = ciWidth,
        bootN = bootN,
        contrasts = contrasts,
        showRealNames = showRealNames,
        showContrastCode = showContrastCode,
        bogus = bogus,
        simpleScale = simpleScale,
        cvalue = cvalue,
        percvalue = percvalue,
        simpleScaleLabels = simpleScaleLabels,
        scaling = scaling,
        tableOptions = tableOptions,
        mediatorsTerms = mediatorsTerms,
        moderatorsTerms = moderatorsTerms)

    results <- jammGLMResults$new(
        options = options)

    analysis <- jammGLMClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
