
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `jamm`=list(
        `type`="software", 
        `author`="Gallucci, M.", 
        `year`=2019, 
        `title`="jAMM: jamovi Advanced Mediation Models", 
        `publisher`="[jamovi module]. Retrieved from https://jamovi-amm.github.io/", 
        `url`="https://jamovi-amm.github.io/"))
