
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `jamm`=list(
        `type`="software", 
        `author`="Gallucci, M.", 
        `year`=2020, 
        `title`="jAMM: jamovi Advanced Mediation Models", 
        `publisher`="[jamovi module]. Retrieved from https://jamovi-amm.github.io/", 
        `url`="https://jamovi-amm.github.io/"), 
    `lavaan`=list(
        `type`="article", 
        `author`="Rosseel, Y.", 
        `year`=2019, 
        `title`="lavaan: An R Package for Structural Equation Modeling", 
        `publisher`="Journal of Statistical Software, 48(2), 1-36", 
        `url`="http://www.jstatsoft.org/v48/i02/"), 
    `diagram`=list(
        `type`="software", 
        `year`=2019, 
        `author`="Soetaert, K.", 
        `title`="diagram: Functions for Visualising Simple Graphs (Networks), Plotting Flow Diagrams", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=diagram", 
        `url`="https://cran.r-project.org/package=diagram"))
