
# This file is automatically generated, you probably don't want to edit this

jammGLMOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jammGLMOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            mediators = NULL,
            factors = NULL,
            covs = NULL,
            modelTerms = NULL,
            ciType = "standard",
            ciWidth = 95,
            bootN = 1000,
            contrasts = NULL,
            showRealNames = TRUE,
            showContrastCode = FALSE,
            simpleScale = "mean_sd",
            cvalue = 1,
            percvalue = 25,
            simpleScaleLabels = "labels",
            scaling = NULL,
            tableOptions = list(
                "beta",
                "component"),
            pathOptions = list(
                "suggested"),
            mediatorsTerms = list(
                list()),
            moderatorsTerms = list(
                list()),
            missing = "listwise",
            diagram = "conceptual",
            diag_paths = "est",
            diag_labsize = "medium",
            diag_shape = "rectangle",
            diag_abbrev = "0",
            diag_offset = FALSE, ...) {

            super$initialize(
                package="jamm",
                name="jammGLM",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..mediators <- jmvcore::OptionVariables$new(
                "mediators",
                mediators,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms,
                default=NULL)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "standard",
                    "bca",
                    "perc",
                    "norm",
                    "none"),
                default="standard")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..showRealNames <- jmvcore::OptionBool$new(
                "showRealNames",
                showRealNames,
                default=TRUE)
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..simpleScale <- jmvcore::OptionList$new(
                "simpleScale",
                simpleScale,
                options=list(
                    "mean_sd",
                    "percent"),
                default="mean_sd")
            private$..cvalue <- jmvcore::OptionNumber$new(
                "cvalue",
                cvalue,
                default=1)
            private$..percvalue <- jmvcore::OptionNumber$new(
                "percvalue",
                percvalue,
                default=25,
                min=5,
                max=50)
            private$..simpleScaleLabels <- jmvcore::OptionList$new(
                "simpleScaleLabels",
                simpleScaleLabels,
                options=list(
                    "labels",
                    "values",
                    "values_labels"),
                default="labels")
            private$..scaling <- jmvcore::OptionArray$new(
                "scaling",
                scaling,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "scaling",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "centered",
                                "standardized",
                                "none"),
                            default="centered"))))
            private$..tableOptions <- jmvcore::OptionNMXList$new(
                "tableOptions",
                tableOptions,
                options=list(
                    "component",
                    "beta",
                    "regression"),
                default=list(
                    "beta",
                    "component"))
            private$..pathOptions <- jmvcore::OptionNMXList$new(
                "pathOptions",
                pathOptions,
                options=list(
                    "suggested"),
                default=list(
                    "suggested"))
            private$..mediatorsTerms <- jmvcore::OptionArray$new(
                "mediatorsTerms",
                mediatorsTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "mediatorsTerms",
                    NULL))
            private$..moderatorsTerms <- jmvcore::OptionArray$new(
                "moderatorsTerms",
                moderatorsTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "moderatorsTerms",
                    NULL))
            private$..missing <- jmvcore::OptionList$new(
                "missing",
                missing,
                options=list(
                    "listwise",
                    "ml"),
                default="listwise")
            private$..diagram <- jmvcore::OptionList$new(
                "diagram",
                diagram,
                options=list(
                    "conceptual",
                    "statistical"),
                default="conceptual")
            private$..diag_paths <- jmvcore::OptionList$new(
                "diag_paths",
                diag_paths,
                options=list(
                    "est",
                    "stand",
                    "hide"),
                default="est")
            private$..diag_labsize <- jmvcore::OptionList$new(
                "diag_labsize",
                diag_labsize,
                options=list(
                    "small",
                    "medium",
                    "large",
                    "vlarge"),
                default="medium")
            private$..diag_shape <- jmvcore::OptionList$new(
                "diag_shape",
                diag_shape,
                options=list(
                    "rectangle",
                    "square",
                    "circle",
                    "ellipse",
                    "diamond"),
                default="rectangle")
            private$..diag_abbrev <- jmvcore::OptionList$new(
                "diag_abbrev",
                diag_abbrev,
                options=list(
                    "0",
                    "5",
                    "10",
                    "15",
                    "20",
                    "25"),
                default="0")
            private$..diag_offset <- jmvcore::OptionBool$new(
                "diag_offset",
                diag_offset,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..mediators)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..ciType)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showRealNames)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..simpleScale)
            self$.addOption(private$..cvalue)
            self$.addOption(private$..percvalue)
            self$.addOption(private$..simpleScaleLabels)
            self$.addOption(private$..scaling)
            self$.addOption(private$..tableOptions)
            self$.addOption(private$..pathOptions)
            self$.addOption(private$..mediatorsTerms)
            self$.addOption(private$..moderatorsTerms)
            self$.addOption(private$..missing)
            self$.addOption(private$..diagram)
            self$.addOption(private$..diag_paths)
            self$.addOption(private$..diag_labsize)
            self$.addOption(private$..diag_shape)
            self$.addOption(private$..diag_abbrev)
            self$.addOption(private$..diag_offset)
        }),
    active = list(
        dep = function() private$..dep$value,
        mediators = function() private$..mediators$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        modelTerms = function() private$..modelTerms$value,
        ciType = function() private$..ciType$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        contrasts = function() private$..contrasts$value,
        showRealNames = function() private$..showRealNames$value,
        showContrastCode = function() private$..showContrastCode$value,
        simpleScale = function() private$..simpleScale$value,
        cvalue = function() private$..cvalue$value,
        percvalue = function() private$..percvalue$value,
        simpleScaleLabels = function() private$..simpleScaleLabels$value,
        scaling = function() private$..scaling$value,
        tableOptions = function() private$..tableOptions$value,
        pathOptions = function() private$..pathOptions$value,
        mediatorsTerms = function() private$..mediatorsTerms$value,
        moderatorsTerms = function() private$..moderatorsTerms$value,
        missing = function() private$..missing$value,
        diagram = function() private$..diagram$value,
        diag_paths = function() private$..diag_paths$value,
        diag_labsize = function() private$..diag_labsize$value,
        diag_shape = function() private$..diag_shape$value,
        diag_abbrev = function() private$..diag_abbrev$value,
        diag_offset = function() private$..diag_offset$value),
    private = list(
        ..dep = NA,
        ..mediators = NA,
        ..factors = NA,
        ..covs = NA,
        ..modelTerms = NA,
        ..ciType = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..contrasts = NA,
        ..showRealNames = NA,
        ..showContrastCode = NA,
        ..simpleScale = NA,
        ..cvalue = NA,
        ..percvalue = NA,
        ..simpleScaleLabels = NA,
        ..scaling = NA,
        ..tableOptions = NA,
        ..pathOptions = NA,
        ..mediatorsTerms = NA,
        ..moderatorsTerms = NA,
        ..missing = NA,
        ..diagram = NA,
        ..diag_paths = NA,
        ..diag_labsize = NA,
        ..diag_shape = NA,
        ..diag_abbrev = NA,
        ..diag_offset = NA)
)

jammGLMResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jammGLMResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        pathmodelgroup = function() private$.items[["pathmodelgroup"]],
        models = function() private$.items[["models"]],
        regressions = function() private$.items[["regressions"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="GLM Mediation Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`="")),
                refs="jamm"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    pathmodel = function() private$.items[["pathmodel"]],
                    statmodel = function() private$.items[["statmodel"]],
                    pathnotes = function() private$.items[["pathnotes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathmodelgroup",
                            title="Path Model",
                            clearWith=list(
                    "dep",
                    "mediatorsTerms",
                    "modelTerms",
                    "moderatorsTerms"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="pathmodel",
                            title="Conceptual Diagram",
                            width=800,
                            height=600,
                            renderFun=".showConceptualDiagram",
                            clearWith=list(
                                "dep",
                                "mediatorsTerms",
                                "modelTerms",
                                "moderatorsTerms",
                                "pathOptions",
                                "diagram",
                                "diag_labsize",
                                "diag_shape",
                                "diag_abbrev"),
                            refs="diagram",
                            visible="(diagram:conceptual)"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="statmodel",
                            title="Statistical Diagram",
                            width=800,
                            height=600,
                            renderFun=".showStatDiagram",
                            clearWith=list(
                                "dep",
                                "mediatorsTerms",
                                "modelTerms",
                                "moderatorsTerms",
                                "pathOptions",
                                "diagram",
                                "diag_offset",
                                "diag_labsize",
                                "diag_shape",
                                "diag_abbrev",
                                "diag_paths"),
                            refs="diagram",
                            visible="(diagram:statistical)"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pathnotes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="info", 
                                    `type`="text", 
                                    `title`="Diagram notes"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    moderationEffects = function() private$.items[["moderationEffects"]],
                    main = function() private$.items[["main"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Mediation",
                            clearWith=list(
                    "dep",
                    "mediators",
                    "factors",
                    "covs"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="moderationEffects",
                            title="Moderation effects (interactions)",
                            visible=FALSE,
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "fixedIntercept",
                                "simpleScale"),
                            columns=list(
                                list(
                                    `name`="mod", 
                                    `title`="Moderator", 
                                    `combineBelow`=TRUE, 
                                    `type`="text"),
                                list(
                                    `name`="target", 
                                    `title`="Interaction", 
                                    `type`="text"),
                                list(
                                    `name`="label", 
                                    `title`="Contrasts", 
                                    `visible`=FALSE, 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `visible`="(tableOptions:beta)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Indirect and Total Effects",
                            refs="lavaan",
                            clearWith=list(
                                "dep",
                                "modelTerms",
                                "contrasts",
                                "fixedIntercept",
                                "simpleScale",
                                "ciType"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="source", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="label", 
                                    `title`="Contrasts", 
                                    `visible`=FALSE, 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `visible`="(tableOptions:beta)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(showContrastCode)",
                            clearWith=list(
                                "contrasts",
                                "showContrastCode"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="$key",
                                visible="(showContrastCode)",
                                columns=list(
                                    list(
                                        `name`="rnames", 
                                        `title`="Name", 
                                        `type`="text"),
                                    list(
                                        `name`="clabs", 
                                        `title`="Contrast", 
                                        `type`="text")))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    overall = function() private$.items[["overall"]],
                    mediator_regressions = function() private$.items[["mediator_regressions"]],
                    full = function() private$.items[["full"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="regressions",
                            title="",
                            clearWith=list(
                    "dep",
                    "contrasts",
                    "scaling"))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                anova = function() private$.items[["anova"]],
                                regression = function() private$.items[["regression"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="overall",
                                        title="Total effects",
                                        clearWith=list(
                    "dep",
                    "contrasts",
                    "scaling"))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="anova",
                                        title="ANOVA Table",
                                        visible="(tableOptions:regression)",
                                        columns=list(
                                            list(
                                                `name`="rsquared", 
                                                `title`="R-squared", 
                                                `type`="number"),
                                            list(
                                                `name`="f", 
                                                `type`="number", 
                                                `title`="F"),
                                            list(
                                                `name`="df1", 
                                                `title`="df1", 
                                                `type`="number"),
                                            list(
                                                `name`="df2", 
                                                `title`="df2", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="p", 
                                                `type`="number", 
                                                `format`="zto,pvalue"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="regression",
                                        title="Regression Table",
                                        visible="(tableOptions:regression)",
                                        columns=list(
                                            list(
                                                `name`="source", 
                                                `title`="Names", 
                                                `type`="text", 
                                                `visible`="(showRealNames)"),
                                            list(
                                                `name`="label", 
                                                `title`="Effect", 
                                                `type`="text"),
                                            list(
                                                `name`="estimate", 
                                                `title`="Estimate", 
                                                `type`="number"),
                                            list(
                                                `name`="se", 
                                                `title`="SE", 
                                                `type`="number"),
                                            list(
                                                `name`="cilow", 
                                                `type`="number", 
                                                `title`="Lower", 
                                                `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                            list(
                                                `name`="cihig", 
                                                `type`="number", 
                                                `title`="Upper", 
                                                `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                            list(
                                                `name`="beta", 
                                                `type`="number", 
                                                `title`="\u03B2", 
                                                `visible`="(tableOptions:beta)"),
                                            list(
                                                `name`="df", 
                                                `title`="df", 
                                                `type`="number"),
                                            list(
                                                `name`="t", 
                                                `title`="t", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="p", 
                                                `type`="number", 
                                                `format`="zto,pvalue"))))}))$new(options=options))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="mediator_regressions",
                            title="Mediator Model",
                            clearWith=list(
                                "dep",
                                "contrasts",
                                "scaling"),
                            template=R6::R6Class(
                                inherit = jmvcore::Group,
                                active = list(
                                    anova = function() private$.items[["anova"]],
                                    regression = function() private$.items[["regression"]]),
                                private = list(),
                                public=list(
                                    initialize=function(options) {
                                        super$initialize(
                                            options=options,
                                            name="undefined",
                                            title="",
                                            clearWith=list())
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="anova",
                                            title="ANOVA",
                                            columns=list(
                                                list(
                                                    `name`="rsquared", 
                                                    `title`="R-squared", 
                                                    `type`="number"),
                                                list(
                                                    `name`="f", 
                                                    `type`="number", 
                                                    `title`="F"),
                                                list(
                                                    `name`="df1", 
                                                    `title`="df1", 
                                                    `type`="number"),
                                                list(
                                                    `name`="df2", 
                                                    `title`="df2", 
                                                    `type`="number"),
                                                list(
                                                    `name`="p", 
                                                    `title`="p", 
                                                    `type`="number", 
                                                    `format`="zto,pvalue"))))
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="regression",
                                            title="Regression",
                                            visible="(tableOptions:regression)",
                                            columns=list(
                                                list(
                                                    `name`="source", 
                                                    `title`="Names", 
                                                    `type`="text", 
                                                    `visible`="(showRealNames)"),
                                                list(
                                                    `name`="label", 
                                                    `title`="Effect", 
                                                    `type`="text"),
                                                list(
                                                    `name`="estimate", 
                                                    `title`="Estimate", 
                                                    `type`="number"),
                                                list(
                                                    `name`="se", 
                                                    `title`="SE", 
                                                    `type`="number"),
                                                list(
                                                    `name`="cilow", 
                                                    `type`="number", 
                                                    `title`="Lower", 
                                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                                list(
                                                    `name`="cihig", 
                                                    `type`="number", 
                                                    `title`="Upper", 
                                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                                list(
                                                    `name`="beta", 
                                                    `type`="number", 
                                                    `title`="\u03B2", 
                                                    `visible`="(tableOptions:beta)"),
                                                list(
                                                    `name`="df", 
                                                    `title`="df", 
                                                    `type`="number"),
                                                list(
                                                    `name`="t", 
                                                    `title`="t", 
                                                    `type`="number"),
                                                list(
                                                    `name`="p", 
                                                    `title`="p", 
                                                    `type`="number", 
                                                    `format`="zto,pvalue"))))}))$new(options=options)))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                anova = function() private$.items[["anova"]],
                                regression = function() private$.items[["regression"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="full",
                                        title="Full model effects",
                                        clearWith=list(
                    "dep",
                    "contrasts",
                    "scaling"))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="anova",
                                        title="ANOVA Table",
                                        visible="(tableOptions:regression)",
                                        columns=list(
                                            list(
                                                `name`="rsquared", 
                                                `title`="R-squared", 
                                                `type`="number"),
                                            list(
                                                `name`="f", 
                                                `type`="number", 
                                                `title`="F"),
                                            list(
                                                `name`="df1", 
                                                `title`="df1", 
                                                `type`="number"),
                                            list(
                                                `name`="df2", 
                                                `title`="df2", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="p", 
                                                `type`="number", 
                                                `format`="zto,pvalue"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="regression",
                                        title="Regression Table",
                                        visible="(tableOptions:regression)",
                                        columns=list(
                                            list(
                                                `name`="source", 
                                                `title`="Names", 
                                                `type`="text", 
                                                `visible`="(showRealNames)"),
                                            list(
                                                `name`="label", 
                                                `title`="Effect", 
                                                `type`="text"),
                                            list(
                                                `name`="estimate", 
                                                `title`="Estimate", 
                                                `type`="number"),
                                            list(
                                                `name`="se", 
                                                `title`="SE", 
                                                `type`="number"),
                                            list(
                                                `name`="cilow", 
                                                `type`="number", 
                                                `title`="Lower", 
                                                `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                            list(
                                                `name`="cihig", 
                                                `type`="number", 
                                                `title`="Upper", 
                                                `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                            list(
                                                `name`="beta", 
                                                `type`="number", 
                                                `title`="\u03B2", 
                                                `visible`="(tableOptions:beta)"),
                                            list(
                                                `name`="df", 
                                                `title`="df", 
                                                `type`="number"),
                                            list(
                                                `name`="t", 
                                                `title`="t", 
                                                `type`="number"),
                                            list(
                                                `name`="p", 
                                                `title`="p", 
                                                `type`="number", 
                                                `format`="zto,pvalue"))))}))$new(options=options))}))$new(options=options))}))

jammGLMBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jammGLMBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jamm",
                name = "jammGLM",
                version = c(1,1,0),
                options = options,
                results = jammGLMResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

